### ISSUE TITLE
Context not accessible in subscriptions

### ISSUE THREAD

**Issue by theo-coder** [graphql-nexus/nexus#1015]
```ts
export const helloMut = mutationField("hello", {
  type: "String",
  args: {
    name: nonNull(stringArg()),
  },
  resolve: (_, args, ctx) => {
    ctx.pubsub.publish("hello", args.name); // accessible, works well
    return `Hello ${args.name}`;
  },
});

export const helloSub = subscriptionField("hello", {
  type: "String",
  subscribe: async (_root, _args, ctx) => {
    console.log(ctx); // empty object
    return ctx.pubsub.asyncIterator("hello"); // not accessible
  },
  resolve: (payload) => payload,
});
```

**Comment by jcpage** [comment]
What is your transport for sending subscriptions to the server?  If it's a websocket using graphql-ws you have to set the context field in the ServerOptions passed to makeServer/useServer similarly to how you'd set it with Apollo Server.

**Comment by theo-coder** [comment]
> What is your transport for sending subscriptions to the server? If it's a websocket using graphql-ws you have to set the context field in the ServerOptions passed to makeServer/useServer similarly to how you'd set it with Apollo Server.

I am using a simple http server : 
```ts
import { ApolloServer } from "apollo-server-express";
import { makeSchema } from "nexus";
import express from "express";
import { createServer } from "http";
import * as types from "./resolver";
import { SubscriptionServer } from "subscriptions-transport-ws";
import { execute, subscribe } from "graphql";
import * as path from "path";
import { db, pubsub } from "./context";

(async () => {
  const app = express();

  const httpServer = createServer(app);

  const schema = makeSchema({
    types,
    outputs: {
      typegen: path.join(__dirname, "nexus-typegen.d.ts"),
      schema: path.join(__dirname, "schema.gql"),
    },
    contextType: {
      module: path.join(__dirname, "context.ts"),
      export: "Context",
    },
  });
  const server = new ApolloServer({
    schema,
    context: async ({ req, res }) => {
      return { req, res, db, pubsub };
    },
  });

  await server.start();
  server.applyMiddleware({ app });

  const subscriptionServer = SubscriptionServer.create(
    { schema, execute, subscribe },
    { server: httpServer, path: "/graphql" }
  );

  httpServer.listen(4000, () => {
    console.log(
      `[\x1b[36mSERVER\x1b[0m] Listening: http://localhost:4000${server.graphqlPath}`
    );
  });
})();
```

**Comment by jcpage** [comment]
SubscriptionServer creates a web socket server internally (required to get events back from subscriptions unless you implement your own transport/polling/whatever).

I'm more familiar with graphql-ws, but it looks like when using subscription-transport-ws you need to return the context you want to use for the subscription from the onConnect() function.

From [these docs](https://github.com/apollographql/subscriptions-transport-ws):

> onConnect?: (connectionParams: Object, webSocket: WebSocket, context: ConnectionContext) : optional method that called when a client connects to the socket, called with the connectionParams from the client, if the return value is an object, its elements will be added to the context. return false or throw an exception to reject the connection. May return a Promise.

Though looking at the code [here](https://github.com/apollographql/subscriptions-transport-ws/blob/a8bbabfe375090b44d4a8bd028356ec53d48a23a/src/server.ts#L305) the returned value doesn't seem to "add to the context", it just *is* the context...
