### ISSUE TITLE
Typescript error inside extendType > resolve

### ISSUE THREAD

**Issue by StephanePiresLearning** [graphql-nexus/nexus#1020]
### A bit about me

Hi, i'm currently trying to learn new technology stack 

This stack include (GraphQL, Apollo, Prisma, nexus) 

*I'm clearly new  to the  field, my first time trying to do something with database was 4 days ago*

-------------

I'm actually running into a problem  

```ts
// graphql/types/Link.ts
import { objectType, extendType } from 'nexus'

export const Link = objectType({
    name: 'Link',
    definition(t) {
        t.int('id')
        t.string('name')
        t.string('url')
        t.string('description')
        t.string('imageUrl')
        t.string('category')
    },
})

export const LinksQuery = extendType({
    type: 'Query',
    definition(t) {
        t.nonNull.list.field('links', {
            type: 'Link',
            resolve(_parent, _args, ctx) {
                return ctx.prisma.link.findMany()
            },
        })
    },
})
```

Typescript Error : 

<img width="1007" alt="Capture d’écran 2021-12-04 à 16 51 27" src="https://user-images.githubusercontent.com/52931491/144715919-63e6b69f-c47a-49f7-8718-ee55c734f89b.png">

---------

To be honest the Typescript error isn't clear for me.  

After reading the docs and investigating some "exemple repository" i can't come with a solution for this error. 

Any idea of whats happening ?  Some types out of sync ?

--------

If i'm not giving enough information, i will provide a repository to reproduce this error

_Thanks in advance_

Stéphane

----------------

Edited : 

_Ok, after reloading VsCode i don't have the typescript error anymore_

I still have a lot of beginner  questions. Do you have any idea where i can ask question about (Prisma, GraphQL, Apollo, Nexus) ? 

-----

_To be closed, no longer relevant_

**Comment by StephanePiresLearning** [comment]
Just in case, some found  read this. 

My issue was a missmatch between the Prisma Types and the Nexus Types

**Comment by jcubic** [comment]
@Stephane-Pires how did you solve the issue? I use the same libraries and got error when compiling with `tsc`.

**Comment by Stephane-Pires** [comment]
@jcubic Hello, do you still have issues regarding your project ?

**Comment by jcubic** [comment]
@Stephane-Pires No, I was able to fix the issue with some help from chatGPT, it gave me the wrong code but it solved one issue that help me figure out the other problems.

The problem was that I've had nonNull single field, from schema I should always have the connection to other table but prisma type allow to return null for that object when it could not it find (by id). So I just throw an error when item was not found:

```javascript
export const Answer = objectType({
    name: 'Answer',
    description: doc('Answer'),
    definition(t) {
        t.field(AnswerP.answer_id);
        t.field(AnswerP.user_id);
        t.field(AnswerP.question_id);
        t.field(AnswerP.answer);
        t.nonNull.field('user', {
            type: User,
            resolve: async (parent, _args, ctx) => {
                const { user_id } = parent;
                const user = await ctx.prisma.user.findUnique({
                    where: {
                        user_id
                    }
                });
                if (!user) {
                    error(`user with id ${user_id} not found`)
                }
                return user;
            }
        });
    }
});
```

and this solved the issue.
