### ISSUE TITLE
New Release for GraphQL v16?

### ISSUE THREAD

**Issue by adarnon** [graphql-nexus/nexus#1033]
It's been a while since GraphQL v16 was released. Nexus added support for it in the `main` branch a month ago, but the latest Nexus release was in June. Is there a plan for a minor release anytime soon?

**Comment by Arturo-Lopez** [comment]
This would be so much helpful, other Graphql libs use the v16 (mercurius for example) and I cant upgrade them because nexus is still in a older version, seeing other [issues](https://github.com/graphql-nexus/nexus/issues/1019#issuecomment-975752775) I found they have plans of working on the issue this week

**Comment by chemicalkosek** [comment]
FIY you can use `npm install nexus@next` for now if you want GraphQL v16 support

**Comment by jgillick** [comment]
This is the one thing preventing me from switching over to nexus.

**Comment by chemicalkosek** [comment]
@jgillick Just so you know that if that [issue](https://github.com/graphql-nexus/nexus/issues/1019) doesn't affect you, you can go with `npm install nexus@next` which has GraphQL 16 support

**Comment by Manubi** [comment]
Would be nice to finally get it to v16. :)

**Comment by Frosty21** [comment]
tried using `"nexus": "^1.2.0-next.17"` but still doesnt support graphql v16 how would you use patch-package for this scenario?

**Comment by soosap** [comment]
> @jgillick Just so you know that if that [issue](https://github.com/graphql-nexus/nexus/issues/1019) doesn't affect you, you can go with `npm install nexus@next` which has GraphQL 16 support

That's not right. Using the nexus@^1.2.0-next.17 is still at `graphql@^15.3.0`. Nexus cannot be used with graphql-upload anymore, as they have moved on to v16. Does anyone know of some workaround?

**Comment by MikaStark** [comment]
Seems to be solved in 1.3.0

**Comment by Manubi** [comment]
> Seems to be solved in 1.3.0

Where do u find 1.3.0? Latest release is afaik 1.1.0.

**Comment by chemicalkosek** [comment]
> Where do u find 1.3.0? Latest release is afaik 1.1.0.

On npm

**Comment by tgriesser** [comment]
Published 1.3.0 w/ GraphQL 16 support
