### ISSUE TITLE
1.2.0 Release?

### ISSUE THREAD

**Issue by in2lag** [graphql-nexus/nexus#1040]
Hi we stumbled upon the fact that there's `1.2.0` version published in [npm](https://www.npmjs.com/package/nexus/v/1.2.0). But there's no release made in here and I didn't find anything mentioned in docs as well. Is everything good on your side? Didn't someone hijack npm repo?

**Comment by tgriesser** [comment]
It looks like @jasonkuhrt [cut a release](https://twitter.com/JasonKuhrt/status/1487201855214170114)

@jasonkuhrt can you push up the git commit / tags?

**Comment by adarnon** [comment]
Any news? Generally when an open source project publishes a release without a corresponding release in GitHub, it seems pretty fishy...

**Comment by jasonkuhrt** [comment]
I'll try to do this at some point

**Comment by adarnon** [comment]
Same for 1.3.0... :\

**Comment by tgriesser** [comment]
@adarnon I pushed up the git tags for 1.3.0 when I published, I thought that automatically created a release. Just created one by hand.

**Comment by adarnon** [comment]
Thank you!
