### ISSUE TITLE
Support for @defer in NexusJS

### ISSUE THREAD

**Issue by extjbhlego** [graphql-nexus/nexus#1046]
Hello 👋

Is there a plan for supporting `@defer` in NexusJS, and if so, can you share some details about it?

I see that the maintainers have been tagged in the [working group discussions](https://github.com/robrichard/defer-stream-wg/discussions/12#discussioncomment-1813016), but can't find any info about it otherwise.

Thanks!

**Comment by calirvine** [comment]
You can use `@defer` with nexus, it's more a feature of your graphql server than your schema. You need to be on a version of graphql-js that supports it amd using a server that supports it. `graphql-helix` supports it on their current version. 

Checkout this toy app I've been playing around with: https://github.com/calirvine/nexus-pagination 
The below query will defer on contactInfo (which has a random delay between 0-4s to resolve). Parts of this are most likely broken, it's just for exploring defer.

```
query ($first: Int, $after: String) {
  people(first: $first, after: $after) {
    nodes {
      id
      fullname
      ...ContactInfoField @defer
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

fragment ContactInfoField on Person {
  contactInfo {
    email
    phoneNumber
  }
}
```

**Comment by calirvine** [comment]
@extjbhlego I did some playing over the weekend with this, trying to get it to work with Relay, it appears that relay requires that the directive be included in the SDL output in order for it to support defer. I'm not sure if there's a correct way to accomplish this, but as a workaround for now, I've just added a `customPrintSchemaFn` to append the directives to the end.

It's hacky, but it makes the relay compiler happy. If anyone knows a better way to add the directives to the output SDL I'd love to hear about it.

```
const deferDirectivesSdl = `
  directive @defer(
    label: String!
    if: Boolean = true
  ) on FRAGMENT_SPREAD | INLINE_FRAGMENT # Relay only supports fragment spread

  directive @stream(
    label: String!
    initial_count: Int!
    if: Boolean = true
  ) on FIELD
`;

export const schema = makeSchema({
  ...your schema config,
  customPrintSchemaFn: (schema) => {
    return `${printSchema(schema)}\n${deferDirectivesSdl}`;
  },
});
```
