### ISSUE TITLE
Generated nexus schema doesn't work with mercurius (the graphql plugin for fastify). 

### ISSUE THREAD

**Issue by xoldyckk** [graphql-nexus/nexus#1049]
Here's the error :- 
`Type 'NexusGraphQLSchema' is not assignable to type 'GraphQLSchema | { typeDefs: TypeSource; resolvers?: IResolvers<unknown, YogaInitialContext, Record<string, any>, any> | IResolvers<...>[] | undefined; } | undefined'.
  Type 'NexusGraphQLSchema' is missing the following properties from type 'GraphQLSchema': _queryType, _mutationType, _subscriptionType, _directives, and 3 more.`

**Comment by santialbo** [comment]
NexusGraphQLSchema extends GraphQLSchema, so you are likely to have an issue with different versions of `graphql` installed in your node_dependencies. Check your package resolutions and make sure a single instance of `graphql` is installed
