### ISSUE TITLE
I migrated nexus 2.13 to 2.15.1, but after migration it can't start normally

### ISSUE THREAD

**Issue by MagicStarTrace** [graphql-nexus/nexus#1086]
OS version: Centos 7
Docker Version: 20.10.15 

Docker run comand:
docker run  --user=nexus --env='JAVA_OPTS=-server -DjavanetpreferIPv4Stack=true' --env='LAUNCHER_CONF=./conf/jetty.xml ./conf/jetty-requestlog.xml' --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=JAVA_VERSION_MINOR=74 --env=JAVA_VERSION_BUILD=02 --env=JAVA_VERSION_MAJOR=8 --env=CONTEXT_PATH=/ --env=MAX_HEAP=768m --env=MIN_HEAP=512m --env=SONATYPE_WORK=/sonatype-work --volume=/data/nexus:/sonatype-work --volume=/sonatype-work -p 8081:8081 --restart=always  --detach=true sonatype/nexus:2.15.1 /bin/sh -c '${JAVA_HOME}/bin/java   -Dnexus-work=${SONATYPE_WORK} -Dnexus-webapp-context-path=${CONTEXT_PATH}   -Xms${MIN_HEAP} -Xmx${MAX_HEAP}   -cp conf/:lib/*   ${JAVA_OPTS}    org.sonatype.nexus.bootstrap.Launcher ${LAUNCHER_CONF}'

![image](https://user-images.githubusercontent.com/15685376/167244029-d2516937-7cb2-461b-9067-027d524666e0.png)

![image](https://user-images.githubusercontent.com/15685376/167244040-abdfbd06-0222-42cd-aa05-d0bf4baee340.png)

[nexus.log](https://github.com/graphql-nexus/nexus/files/8644663/nexus.log)

I used the 2.13 data volume, please help to see what is the problem

Thank you

**Comment by tgriesser** [comment]
I think you have the wrong Nexus project, this is a Node.js project and is only at version 1.3.0
