### ISSUE TITLE
How to specify query argument: list of Any type?

### ISSUE THREAD

**Issue by geyang** [graphql-nexus/nexus#1096]
A query argument is a list of `Any` object type. 

The payload of the query is a list of objects of mixed schema. I don't want to specify the interface and want to use a catch-all scalar type interface for these.

How do I implement `Any` scalar type for generic object types?

Can I use this as an input argument?

**Comment by santialbo** [comment]
You can create a custom scalar for JSON objects
```ts
import { GraphQLDateTime, GraphQLJSON, GraphQLJSONObject } from "graphql-scalars";
import { arg, asNexusMethod, core } from "nexus";

// make sure this is part of the "import * as allTypes from ..." that is used in the makeSchema call
export const JSONObject = asNexusMethod(GraphQLJSONObject, "jsonObject", "{[key: string]: any}");
export function jsonObjectArg(opts?: Omit<core.NexusArgConfig<"JSONObject">, "type">) {
  return arg({ ...opts, type: "JSONObject" });
}
```
then do

```
  ...
  args: {
    paramx: list(jsonObjectArg())
  }
  ...
```

**Comment by tgriesser** [comment]
Yep what @santialbo suggested is what I'd recommend, a JSON type is likely the closest thing to an `any` type you'll get in GraphQL
