### ISSUE TITLE
Inline resolving doesn't work

### ISSUE THREAD

**Issue by nikolasburk** [graphql-nexus/nexus#13]
I've found this code snippet in the docs, that allows to pass resolvers inline: 

```
const User = objectType("User", (t) => {
  t.id("id", (o) => o.user_id);
  t.id("name", (o) => o.user_name);
  t.id("description", (o) => o.user_description);
});
```

However, when I'm trying to achieve this I am getting an error:

```
~/D/nexus-example $ yarn start
yarn run v1.13.0
warning package.json: No license field
$ ts-node-dev ./src
Using ts-node version 8.0.1, typescript version 3.2.4
[ERROR] 18:48:55 ⨯ Unable to compile TypeScript:
src/index.ts(8,20): error TS2559: Type '(root: any, args: any) => string' has no properties in common with type 'OutputFieldOpts<GraphQLNexusGen, "Query", "test">'.
src/index.ts(8,21): error TS7006: Parameter 'root' implicitly has an 'any' type.
src/index.ts(8,27): error TS7006: Parameter 'args' implicitly has an 'any' type.
```

![image](https://user-images.githubusercontent.com/4058327/51554672-19d6ea00-1e76-11e9-8168-9ef7a790fd68.png)

**Comment by tgriesser** [comment]
What version of nexus are you on? The docs currently reflects what's on the `@alpha` tag `0.7.0-alpha.1`

**Comment by nikolasburk** [comment]
Ah good point, I indeed was on `0.6.2`. However, I just upgraded to `@alpha` (I'm now on `^0.7.0-alpha.1`).

This is my `tsconfig`:

```json
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "dist",
    "strictFunctionTypes": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "lib": [
      "esnext",
      "dom"
    ],
  }
}
```

**Comment by nikolasburk** [comment]
Hmm ok, this must have been related to `nexus-prisma`. I was using `prismaObjectType` and `makePrismaSchema`. Now I went back to just `objectType` and `makeSchema` and it works 🙌
