### ISSUE TITLE
Plan to go to version 1.0.0

### ISSUE THREAD

**Issue by saostad** [graphql-nexus/nexus#219]
Hi, 
I am using this awesome package for my production servers but I have concerns about future changes, is there any plan to bump up the version to 1.0.0?

**Comment by brikou** [comment]
nexus is already full of great promises, I'm also interested by the 1.0 roadmap

**Comment by hkjorgensen** [comment]
I'm also very interested in a roadmap for v1. Love the project so far!

**Comment by iddan** [comment]
Can this be closed as version 1.0.0 was released?

**Comment by janpio** [comment]
Yes it certainly can @iddan 👍 

https://github.com/graphql-nexus/nexus/releases/tag/1.0.0
