### ISSUE TITLE
Rename package to nexus

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/nexus#651]
Now that Nexus framework is gone let's take back the name "Nexus".

Any objections @tgriesser?

**Comment by tgriesser** [comment]
Re-re-re name 😛 ? (`gqliteral` -> `nexus` -> `@nexus/schema` -> `nexus`)

But yeah, let's wait until 1.0 so there's less confusion, and since `nexus` got up to `0.30.1`.

We can publish 1.0 to both, but deprecate `@nexus/schema` and un-deprecate `nexus`.

**Comment by jasonkuhrt** [comment]
Yep was thinking the exact same thing, at 1.0

**Comment by Sytten** [comment]
is the decision on framework really final? I would keep the current name IMO for future proofing...
If you want to split in multiple modules its also nicer because you have the @nexus namespace.

**Comment by jasonkuhrt** [comment]
> is the decision on framework really final? 

Yep, if the framework comes back it will not be called Nexus

**Comment by Sytten** [comment]
Make sense, I still think namespacing the modules is not a bad idea either since I see nexus as more of a plugin architecture than a monolith package.

**Comment by jasonkuhrt** [comment]
It think having the package name match what people call it helps. And differentiating nexus from nexus schema, as if they mean something different, is confusing. YANGI

**Comment by jasonkuhrt** [comment]
closed by 80ad53135c98ab3cc816f7c6ddd652ce12a251ce
