### ISSUE TITLE
Ability to control the name of connection and edge types

### ISSUE THREAD

**Issue by migueloller** [graphql-nexus/nexus#697]
It is currently not possible to control the names of the types generated by the connection plugin, specifically the connection and edge types. When extended, these types add an `_` between the base field name and `Edge` or `Connection`, resulting in types named like `WorkspaceUser_Edge` or `WorkspaceUser_Connection`. It would be desirable to have these be named `WorkspaceUserEdge` and `WorkspaceUserConnection`, respectively.

**Comment by migueloller** [comment]
Would a PR be accepted that adds a `getEdgeName` and `getConnectionName` field to the `PluginConfig` and `ConnectionFieldConfig` types? This would be an opt-in non-breaking change that would allow users to do this:

```typescript
// at plugin level
import { makeSchema, connectionPlugin } from '@nexus/schema'
const schema = makeSchema({
  // ... types, etc,
  plugins: [
    // ... other plugins
    connectionPlugin({
      getEdgeName(fieldName, parentTypeName, fieldConfig, pluginConfig) {
        return `${parentTypeName}${upperFirst(fieldName)}Edge`
      }
    }),
  ],
})

// at field level
import { connectionFromArray } from 'graphql-relay'
export const usersQueryField = queryField((t) => {
  t.connectionField('users', {
    type: User,
    async resolve(root, args, ctx, info) {
      return connectionFromArray(await ctx.resolveUserNodes(), args)
    },
    getEdgeName(fieldName, parentTypeName, fieldConfig, pluginConfig) {
      return `${parentTypeName}${upperFirst(fieldName)}Edge`
    }
  })
})
```

**Comment by tgriesser** [comment]
I think this could be useful, will look into adding something like this along with some other Connection fixes I'm planning on adding before 1.0

**Comment by fikrikarim** [comment]
I'm interested in this change. I could also help to create a PR if there's any approved specification for the changes.

Is there any reason why the schema add an underscore, `_`, when we use a custom edge or a custom connection?

**Comment by migueloller** [comment]
@tgriesser, looks like v1 shipped. Congrats! Still interested on adding something like this soon?

I'll gladly do a PR if there's a specific API you have in mind.

**Comment by tgriesser** [comment]
Thanks! Yeah, this is still something I'd like to get in there in a minor version release.

I was thinking about it though, and wanted to make sure I fully understood the use case. I believe the `_` is only added if you're extending on a per-field basis, rather than for the extension globally. 

I think I assumed you'd normally want to extend globally, potentially with multiple different instances of the `connectionPlugin` in the `plugins` config, so I was looking to see if there were more concrete examples of where/how you were extending. The code around connections is already pretty rough, so just wanted to make sure the use case was fully understood before throwing more code at it.

**Comment by migueloller** [comment]
That's a great question!

So we're currently migrating our entire API from SDL-first to code-first and after trying GraphQL.js together with GraphQL Code Generator and Nexus, we decided to go with Nexus. It's a great library, so thank your for all your work and making it open source.

One of the requirements we have for the migration is to keep the schema unchanged so that we can change the API code without affecting any clients. We have some connection types that have a `totalCount` field and we used a field-level extension (as opposed to a global extension) and that works like a charm. Where the name of the type comes in, though, is that for the edges, our API followed the naming pattern: `${parentType}${upperFirst(fieldName)}Edge`. So for example, if an `Invoice` type has an `items` field with a connection of `InvoiceItem`, we would have the following types (in SDL):

```graphql
# ...

type InvoiceItemsConnection {
  pageInfo: PageInfo!
  edges: [InvoiceItemsEdge]!
}

type Invoice {
  items: InvoiceItemsConnection!
}
```

Now, it just so happens that Nexus' naming convention is different than the one we had: https://github.com/graphql-nexus/nexus/blob/bef7786a7d25f04f376d2598284687201214ae7b/src/plugins/connectionPlugin.ts#L998-L1004

Well, not entirely, if the type is extended, the convention is the same, except for the `_`. Anyway, we thought that if we have the ability to control the name of the type then we would just be able to override the default name, use the plugin, and preserve the type names as we migrate the schema.

**Comment by tgriesser** [comment]
@migueloller Cool, that all makes sense. If you have the time to take a shot at it with some tests, I'd definitely be up for reviewing & getting it landed. Otherwise I can try and get around to it sometime in the next couple of days.

**Comment by migueloller** [comment]
@tgriesser, just opened #744. Thanks!
