### ISSUE TITLE
Error "t.resolveType is not a function" on interfaceType with nexus 1.0

### ISSUE THREAD

**Issue by LRipi** [graphql-nexus/nexus#739]
Hi!

I am currently encountering an error during the instantiation of `interfaceType`.
I'm trying to implement an interface on two `objectType`.

To create an interface, we just set the next parameters :
```
const TypeEnum = enumType({
  description: 'The Document Type that could be applied.',
  members: ['DRAFT', 'TEMPLATE'],
  name: 'DocumentTypeEnum',
});

const Document = interfaceType({
  definition(t) {
    t.nonNull.string('_id', {
      description: 'The ID of the document',
    });
    t.nonNull.field('type', {
      description: "The document's type",
      type: TypeEnum,
    });
  },
  description: 'This type describe the different document.',
  name: 'Document',
  resolveType(doc) {
    let typename = null;
    if (doc.type === 'DRAFT') typename = 'DocumentDraft';
    if (doc.type === 'TEMPLATE') typename = 'DocumentTemplate';

    if (!typename)
      throw new Error('Could not resolve the type of data passed to interface type "Document"');
    return typename;
  },
})
```
According to the documentation about [centralized strategy](https://nexusjs.org/docs/guides/abstract-types#centralized-strategy-resolvetype), we set the `resolveType` which return the *typename* of our objects.

The objects are the following:

```
const DocumentTemplate = objectType({
  definition(t) {
    t.implements([Document]);
    // And more fields right here
  },
  name: 'DocumentTemplate',
});

const DocumentDraft = objectType({
  definition(t) {
    t.implements([Document]);
    // And more fields right here
  },
  name: 'DocumentDraft',
});
```

But when I try to launch my application, the next error happen: 
`(node:5226) UnhandledPromiseRejectionWarning: TypeError: t.resolveType is not a function`.

Before the v1.0, we had the `t.resolveType()` that doesn't exist anymore and it has been replaced by the `resolveType` function at the root of the `interfaceType`.

Is that a bug or did I forgot something?

**Comment by JCMais** [comment]
have you solved this?
