### ISSUE TITLE
Method of generating GraphQL

### ISSUE THREAD

**Issue by Mark-Panda** [graphql-nexus/nexus#740]
I want a way to generate .graphql files。
Can you help me？

**Comment by mohsin51** [comment]
You can generate graphql artifacts by running your main file in which your are using nexus makeSchema. 
e.g in my case it's 

`NODE_ENV=development node -r ts-node/register/transpile-only -r tsconfig-paths/register src/app/server/schema/index.ts`

and schema index would be something like

`

const schema = makeSchema({
  types: [
    types,
    queries,
    mutations,
  ],
  plugins: [nexusSchemaPrisma(
    {
      experimentalCRUD: true,
      outputs: {
        typegen: path.join(basePath, 'typegen-nexus-plugin-prisma.d.ts'),
      },
    },
  )],
  typegenAutoConfig: {
    sources: [
      {
        source: '@prisma/client',
        alias: 'prisma',
      },
      {
        source: require.resolve('./context'),
        alias: 'Context',
      },
    ],
    contextType: 'Context.Context',
  },
  shouldGenerateArtifacts: NODE_ENV !== 'production',
  shouldExitAfterGenerateArtifacts: process.argv.includes('--nexus-exit'),
  outputs: {
    schema: path.join(basePath, 'schema.graphql'),
    typegen: path.join(basePath, 'nexus.ts'),
  },
});
`

**Comment by Mark-Panda** [comment]
ok,i know
