### ISSUE TITLE
nexus-plugin-prisma: Nexus BatchPayload Type Generation Mismatch

### ISSUE THREAD

**Issue by jonathancslynn** [graphql-nexus/nexus#741]
I know this issue was resolved in previous versions  (https://github.com/graphql-nexus/nexus-plugin-prisma/issues/341, https://github.com/graphql-nexus/nexus-plugin-prisma/pull/441), but I think I am experiencing the same issue where BatchPayload type cannot be found on `PrismaClient` in the autogenerated `nexus-typegen.ts` file.

My Package Versions: 
```
@prisma/client: 2.13.0
nexus: 1.0.0
nexus-plugin-prisma: 0.27.0
```

It's usage in `nexus-typegen.ts` (and where the error arises):
```ts
export interface NexusGenObjects {
  BatchPayload: PrismaClient.BatchPayload;  // Error: "~/node_modules/.prisma/client/index"' has no exported member 'BatchPayload'
  Mutation: {};
}
```
How it's defined in `node_modules/.prisma/client/index.d.ts`:
```ts
export namespace Prisma {

/**
   * Batch Payload for updateMany & deleteMany
   */

  export type BatchPayload = {
    count: number
  }
}
```

This is not an issue with package versions:
```
@prisma/client: 2.12.1
nexus: 0.19.0
nexus-plugin-prisma: 0.25.0
```

It seems that the issue can be resolve by manually modifying the `nexus-typegen.ts` file for now:
```ts
export interface NexusGenObjects {
  BatchPayload: PrismaClient.Prisma.BatchPayload; 
  Mutation: {};
}
```

**Comment by jonathancslynn** [comment]
Turns out the solution lies in how `makeSchema` is configured
Currently, nexus' docs say:
```ts
  // api/schema.ts
import { makeSchema } from 'nexus'
import { join } from 'path'
export const schema = makeSchema({
  types: [], // 1
  outputs: {
    typegen: join(__dirname, '..', 'nexus-typegen.ts'), // 2
    schema: join(__dirname, '..', 'schema.graphql'), // 3
  },
})
```
https://nexusjs.org/docs/getting-started/tutorial/chapter-setup-and-first-query#creating-our-app-layout

The above issue can be solved by changing `nexus-typegen.ts` to a definition file such as `nexus-typgen.d.ts`

**Comment by mingchuno** [comment]
@jonathancslynn I change to `*.d.ts` but cannot solve the issue.
