### ISSUE TITLE
Prisma scalar is mapped to the wrong GraphQL scalar

### ISSUE THREAD

**Issue by chriskjaer** [graphql-nexus/nexus#742]
According to the [nexus-plugin-prisma docs](https://nexusjs.org/docs/plugins/prisma/api#scalar). `cuid` and `uuid` should map to `ID`. However they are mapped to `String` instead.

**Example:**

prisma.schema
```prisma
model Post {
  id      String @default(cuid()) @id
}
```
types.ts
```ts
objectType({
  name: 'Post',
  definition(t) {
    t.model.id()
  },
}),
```

Should generate the following schema:

```graphql
type Post {
  id: ID!
}
```

but is generating

```graphql
type Post {
  id: String!
}
```

## Steps to reproduce:

Clone the `hello-world` example in the nexus-plugin-prisma github repo: https://github.com/graphql-nexus/nexus-plugin-prisma/tree/main/examples/hello-world

Run `yarn nexus:reflect` and see that the ids in the generated graphql schema are all `String`

**Comment by Sytten** [comment]
Prisma plugin is not supported anymore, see https://github.com/prisma/nexus-prisma/
