### ISSUE TITLE
Setting nonNullDefaults doesn't affect typegen

### ISSUE THREAD

**Issue by edjiang** [graphql-nexus/nexus#750]
Set non null input defaults. 

```graphql
mutationType({
    'nonNullDefaults': {
        input: true
    },
    definition(t) { }
}
)
```

Then define this a query with an input:

```js
queryField('user', {
    type: 'User',
    args: {
        id: stringArg()
    },
    resolve(_root, args, context) {
        return db.user.findUnique({
            where: {
                id: args.id
            }
        })
    }
})
```

Type Error:

```
api/graphql/users.ts - error TS2322: Type 'string | null | undefined' is not assignable to type 'string | undefined'.
  Type 'null' is not assignable to type 'string | undefined'.
```

We can fix this by adding the `nonNull()` function around the `stringArg()`, but this ideally wouldn't be necessary.

**Comment by hpurra** [comment]
you need to pass `nonNullDefaults` to `makeSchema` https://nexusjs.org/docs/api/make-schema#nonnulldefaults

**Comment by edjiang** [comment]
My understanding is that you can define defaults at the type level, in this example. 

https://nexusjs.org/docs/guides/nullability#example-nullability-flipped-at-type-level

The GraphQL SDL is generated correctly, only the Typescript typegen is not.

**Comment by jasonkuhrt** [comment]
Modifying `mutationType` only affects `mutationField`. In this case what you want to do is change defaults on `queryType`.

**Comment by edjiang** [comment]
Oops, silly mistake. Thanks!
