### ISSUE TITLE
Let the user know there will be a type error sooner in docs section 2

### ISSUE THREAD

**Issue by MatthewCaseres** [graphql-nexus/nexus#753]
https://nexusjs.org/docs/getting-started/tutorial/chapter-writing-your-first-schema/#your-first-home-grown-query

In this section I got a type error, which kind of threw me into a panic. I had to scroll down a bit to realize this is expected, should the user be warned of this a bit earlier?

**Comment by jasonkuhrt** [comment]
PR welcome!

**Comment by MatthewCaseres** [comment]
https://github.com/graphql-nexus/nexus/pull/776

Changed a couple of other things as well.
