### ISSUE TITLE
Wire Up the Context section, contextType missing 'export'

### ISSUE THREAD

**Issue by MatthewCaseres** [graphql-nexus/nexus#754]
![image](https://user-images.githubusercontent.com/43053796/103085427-3e2e2a80-45a7-11eb-8254-2d8abc4929df.png)

This is after following the instructions in the docs for the last code snippet of this - https://nexusjs.org/docs/getting-started/tutorial/chapter-adding-mutations-to-your-api/#wire-up-the-context.

It seems 'alias' should be changed to 'export'.

**Comment by MatthewCaseres** [comment]
After changing 'alias' to 'export', I am now having another issue further in the docs - 
![image](https://user-images.githubusercontent.com/43053796/103085838-7eda7380-45a8-11eb-9746-6d2ceeecd17f.png)
Here is the code - https://github.com/MatthewCaseres/nexus-reproduction/tree/1.0

**Comment by jasonkuhrt** [comment]
The docs have since been updated. Thanks for raising @MatthewCaseres.

**Comment by Delivator** [comment]
Has the actual website (https://nexusjs.org/docs/getting-started/tutorial/chapter-adding-mutations-to-your-api) also updated? I just ran into this issue

**Comment by jasonkuhrt** [comment]
@Delivator looks wrong, pr welcome, will try to fix soon
