### ISSUE TITLE
What is nexus / nexus schema / nexus framework / nexus js / nexus experiment?

### ISSUE THREAD

**Issue by gustawdaniel** [graphql-nexus/nexus#761]
Can anyone explain current and historic naming of these things?

I see this repository is called "nexus".

I is linked with page "nexusjs"

https://nexusjs.org/

But I know that "nexus graphql framework" was called in this way and is unmaintained and now called "nexus experiment". 

I looking for "nexus schema" (without unmaintained framework) but after update of packages like "nexus plugin prisma" i see errors:

```
Cannot find module 'nexus' or its corresponding type declarations.
```

I expected that "nexus plugin prisma" will use now pure "nexus schema" without "framework" but I see imports like these

```
import { core } from 'nexus';
```

in `node_modules/nexus-plugin-prisma/dist/utils.d.ts`

But when I typed in google "nexus framework migration guide" I see working page:

https://nexusjs.org/docs/adoption-guides/neuxs-framework-prisma-users

that should be marked as `depreciated / unmaintained`

There is link to migration from nexus to nexus-schema

https://nexusjs.org/docs/adoption-guides/nexus-framework-users

but now it is called Nexus (without schema)

![Screenshot from 2020-12-30 16-09-53](https://user-images.githubusercontent.com/16663028/103361211-6fcc5780-4ab9-11eb-9719-50693cb47c3e.png)

When in annoucment

https://github.com/prisma-labs/graphql-framework-experiment

It is called Nexus schema

![Screenshot from 2020-12-30 16-10-05](https://user-images.githubusercontent.com/16663028/103361507-84105480-4ab9-11eb-98ba-66b995cf0eb3.png)

Now nexus schema is depreciated:

https://www.npmjs.com/package/@nexus/schema

![Screenshot from 2020-12-30 16-12-47](https://user-images.githubusercontent.com/16663028/103362523-c89bf000-4ab9-11eb-8c78-d1c4d4cdc512.png)

Sorry for this long issue, but somebody responsible for these decisions (of changes in naming) should not manage this project.

I initially loved it but now I do not want to use any tools with nexus in name because of terrible management of communication with programmers and outdated documentation.

Please imagine, how much chaos and confusion will it generate when you are searching for solution and you see materials with such many names and any of them should be matched with dates range to check what author mean by this name.

**Comment by Sytten** [comment]
Yeah this was not great and that is why I advised to stick to the `@nexus/schema` name.
Anyway long story short:
1. Original package was called nexus
2. Package was renamed nexus/schema and nexus was rebranded for the framework around v0.12 if I remember
3. Framework is abandoned and moved to nexus-experiment
4. Nexus schema is rerenamed nexus on the v1 release

Should be better getting forward, but lots of small places remain with old names.

**Comment by jdevng** [comment]
As green, i have a hard time telling what nexus does and how it fits in to something like apollo or a prisma interface.

**Comment by Sytten** [comment]
It defines the graphql schema using code instead of writing it in GraphQL directly. Honestly I would start with just a basic apollo server to start, add prisma after and then translate to nexus. Otherwise you will be lost in the concept. I don't even use the nexus prisma plugin.

**Comment by ahmedosama5200** [comment]
> I don't even use the nexus prisma plugin.
Why ? What's wrong with it ?

**Comment by Sytten** [comment]
Nothing is wrong, I just don't like autogenerated resolvers were I don't control every security aspect of it. Proper access control in a multi-tenant architecture is hard enough without allowing the users to query anything on the DB.

**Comment by ahmedosama5200** [comment]
I don't mean the experimental crud feature. I mean the model projection part of it using `t.model`.
If you don't use it, you should somehow make use of prisma autogenerated types using nexus `sourceTypes`. The plugin is doing pretty much the same thing.

**Comment by Sytten** [comment]
Agreed that is what I am doing. I still prefer it that way since I can easily override the models if need be and it forces a decoupling of the interface/user facing side from the storage side. I have not really look into the plugin a lot to be honest.

**Comment by bbbryan14** [comment]
I wish I could give a million thumbs up on this issue

**Comment by jasonkuhrt** [comment]
Answered by @Sytten thanks. PRs to update old ID names are welcome if found.
