### ISSUE TITLE
This part of prisma plugin docs is probably deprecated

### ISSUE THREAD

**Issue by ahmedosama5200** [graphql-nexus/nexus#767]
I am not able to find any of the apis mentioned in this [section](https://nexusjs.org/docs/plugins/prisma/overview#plugin-settings)

What is that about ?

**Comment by jasonkuhrt** [comment]
Refer to the examples and make sure you are using a recent version. https://nexusjs.org/docs/plugins/prisma/overview#examples

**Comment by ahmedosama5200** [comment]
`import { use } from 'nexus`

I have the latest version (1.0.0), I can not import this `use` function which is mention in the examples link you gave me

**Comment by jasonkuhrt** [comment]
@ahmedosama5200 looks like you're using the nexus framework. Please see https://nexusjs.org/docs/adoption-guides/nexus-framework-users

**Comment by jasonkuhrt** [comment]
Ah sorry yes. Thanks @ahmedosama5200

**Comment by jasonkuhrt** [comment]
closed by a782944

**Comment by jasonkuhrt** [comment]
And d996212
