### ISSUE TITLE
Default parameter of Arg should make argument non-null

### ISSUE THREAD

**Issue by Akxe** [graphql-nexus/nexus#775]
This is a simple change, where the `default` parameter of `arg` (and its children `intArg`, `booleanArg`, etc) should affect the nullability of the resulting parameter.

```ts
t.string('createMapsUrl', {
	description: 'For internal use only',
	args: {
		typeA: intArg({ }),
		typeB: intArg({ required: true }),
		typeC: intArg({ default: 42 }),
	},
	resolve(_, args) {
		// args.typeA is of type `number | null | undefined`
		// args.typeB is of type `number`
		// args.typeC is of type `number | null | undefined`, but should be of type `number`
	}
};
```

**Comment by jasonkuhrt** [comment]
https://nexusjs.org/docs/guides/nullability#example-args-that-have-default-values

This is fixed in Nexus 1.0

`args.typeC` is now `number | null`.
