### ISSUE TITLE
Support prisma 2.14.0

### ISSUE THREAD

**Issue by ahmedosama5200** [graphql-nexus/nexus#779]
I am getting this warning when upgrading to prisma 2.14
`Warning: nexus-plugin-prisma@0.27.0 does not support @prisma/client@2.14.0. The supported range is: `2.13.x`. This could lead to undefined behaviors and bugs.`

**Comment by mikkelsl** [comment]
Try nexus-plugin-prisma@0.28.0

**Comment by ahmedosama5200** [comment]
Okey, I didn't notice they really pushed an update that quick!
