### ISSUE TITLE
makeSchema's outputs/contextType .ts files need to be replaced with .js in production

### ISSUE THREAD

**Issue by johnnyoshika** [graphql-nexus/nexus#810]
In the tutorial here: https://nexusjs.org/docs/getting-started/tutorial/chapter-adding-mutations-to-your-api#wire-up-the-context

...the following example is given:

```
  outputs: {
    typegen: join(__dirname, '..', 'nexus-typegen.ts'),
    schema: join(__dirname, '..', 'schema.graphql')
  },
  contextType: {                                    // 1
    module: join(__dirname, "./context.ts"),        // 2
    export: "ContextModule",                        // 3
  },
```

When TypeScript files are compiled to JavaScript, references to `nexus-typegen.ts` and  `./context.ts` need to be replaced with `nexus-typegen.js` and  `./context.js` , otherwise those files won't be found. Here's a suggestion on what it can be changed to:

```
  const ext = process.env.NODE_ENV === 'production' ? 'js' : 'ts';

  outputs: {
    typegen: join(__dirname, '..', `nexus-typegen.${ext}`),
    schema: join(__dirname, '..', 'schema.graphql'),
  },
  contextType: {
    module: join(__dirname, `./context.${ext}`),
    export: 'Context',
  },
```

**Comment by santialbo** [comment]
Nexus generates a typescript types file on development which should be compiled by typescript, there's no need to change the extension on the output configuration.
About the contextType, just drop the extension as you would do when you use `import` on your ts files.

```
  outputs: {
    typegen: join(__dirname, '..', `nexus-typegen.ts`),
    schema: join(__dirname, '..', 'schema.graphql'),
  },
  contextType: {
    module: join(__dirname, `./context`),
    export: 'Context',
  },
```

**Comment by crqra** [comment]
Thanks @santialbo. BTW, if anyone comes here because of `sourceTypes` just know that there is a `shouldGenerateArtifacts` flag. Completely missed that out at first.

https://nexusjs.org/docs/api/make-schema#shouldgenerateartifacts-outputs-sourcetypes

**Comment by mohsin51** [comment]
+1

**Comment by johnnyoshika** [comment]
Thanks everyone for the explanation. Closing, as this doesn't seem to be an issue.

**Comment by chrishoermann** [comment]
Run into the same problem, here's my solution:

```typescript
export const schema = makeSchema({
  types: [types, DateTime, JSON],
  outputs: {
    typegen: join(__dirname, "..", "nexus-typegen.ts"),
    schema: join(__dirname, "..", "schema.graphql"),
  },
  sourceTypes: {
    modules: [
      {
        module: require.resolve(".prisma/client/index.d.ts"),
        alias: "prisma",
      },
    ],
  },

  // artifacts should only be generated in development
  shouldGenerateArtifacts: process.env.NODE_ENV === "development",

  // context typings only need to be available in development
  contextType:
    process.env.NODE_ENV === "development"
      ? {
          module: join(__dirname, "./context.ts"),
          alias: "contextModule",
          export: "Context",
        }
      : undefined,
});
```

**Comment by miguelc1221** [comment]
ran into a similar issue, using `tsc` to compile and it can't find the `./context.ts` in the dist folder, my solution was to generate the `typegen` before compiling when in dev but still need the above solution @chrishoermann suggested. Dropping the extension doesn't seem to work ```.......dist/src/api/context for the type context does not exist```

**Comment by arvindell** [comment]
I'm encountering this problem too. My prod build is failing because ctx gets typed as `any`. I used @chrishoermann solution but it only works if I build my project with `NODE_ENV` as development :thinking:
