### ISSUE TITLE
Using types defined in schema, or using types via schema?

### ISSUE THREAD

**Issue by kevin-daniel-hunt** [graphql-nexus/nexus#820]
I have been working with nexus js for a while now, but there are still some issues I am having despite reading the docs.

Sometimes I am defining schemas that I want to use the types for using helper functions.  I know I can use FieldResolver to get the type of a specific field, but sometimes I want to use just the Type of an objectType or enumType I have defined at other places in my code.

Or I could do it the other way around, where I specify a type or interface in my typescript and can then just pass that object into my objectType or enumType definitions. 

Currently when defining types, I have to define this once, using a typescript interface/type I can reference at other points in my code, and once in my schema to be defined for graphql.  Having one place to make changes seems to be the correct pattern but I cannot figure out how to do it...

**Comment by Sytten** [comment]
I believe this should probably be a plugin.

**Comment by jasonkuhrt** [comment]
@kevin-daniel-hunt some examples would be great, but I know what you mean.

Better documenting helper type-level functions would be good.

**Comment by kevin-daniel-hunt** [comment]
As an example, say I define a simple objectType:
```
export const Neighbors = objectType({
  name: 'Neighbors',
  definition(t) {
    t.field('previous', {
      type: 'string',
      nullable: true,
    });
    t.field('next', {
      type: 'string',
      nullable: true,
    });
  },
});
```

How can I now use this Neighbor type in a helper utility function?  Obviously when using this type with nexus you pass the type as a string for nexus to resolve on its own, but I would like to be able to use this type for other utlity functions so if I need to change the shape of this type, I only have to change it in one place, the nexus defintion.

**Comment by kevin-daniel-hunt** [comment]
Edit:  For other people having a similar problem, I beleive I have found a solution:
```
import { SourceValue } from 'nexus/dist/core';

let neighbors: SourceValue<'Neighbors'>  = {
   prev: null,
   next: null
}
```

This appears to appropriately type with the definition of the above nexus schema.  This isn't a exported at the root level of the project which makes me think this isn't meant to be exposed.  And it is also not documented anywhere I can find (though it is in the typehelper file).  This should be documented as it is very very useful.

**Comment by kevin-daniel-hunt** [comment]
For anyone who finds this, its best to just use the generated type file.
