### ISSUE TITLE
How to create a JSON custom scalar type?

### ISSUE THREAD

**Issue by AikoRamalho** [graphql-nexus/nexus#825]
Under old nexus we could create a JSON return type for a resolver like this:
![image](https://user-images.githubusercontent.com/15454141/107579369-c73f0680-6bd3-11eb-824f-f985f2dbe9ab.png)

Right now when I try to do the same I have the following error: 
```Property 'json' does not exist on type 'ObjectDefinitionBlock<"Query">'.```

![image](https://user-images.githubusercontent.com/15454141/107579501-fce3ef80-6bd3-11eb-81af-7b576b65d388.png)

Any help?

**Comment by AikoRamalho** [comment]
Nvm, just realized that I just needed to create a json scalar type and use it on types inside makeSchema.

![image](https://user-images.githubusercontent.com/15454141/107669423-78937a00-6c70-11eb-9075-5aea2da55dbf.png)

I'm closing it.

**Comment by hryjosn** [comment]
@AikoRamalho The easier way you can try: 

`import { JSONResolver, DateResolver } from 'graphql-scalars'
import { asNexusMethod } from 'nexus'
export const JSON = asNexusMethod(JSONResolver, 'json')
export const Date = asNexusMethod(DateResolver, 'date')
`
This work for me
