### ISSUE TITLE
nexus must be installed as a dependency. Please run `npm install nexus`.

### ISSUE THREAD

**Issue by mohsinamjad** [graphql-nexus/nexus#854]
After building and running the production build, I get this error
`nexus must be installed as a dependency. Please run `npm install nexus`.`
I was getting the same error before for @nexus/schema which is deprecated but in that case, I fixed that issue by marking the module as an external dependency and doing npm install where my main.js was built,
but after upgrading from @nexus/schema to nexus, even that workaround is not working for me, no matter what I do I still get `nexus must be installed` when I run node main.js

**Comment by Sytten** [comment]
I mean you do need nexus as a production dependency (aka it needs to be in your node_modules), so this is expected?
Closing for now, but feel free to comment if this is still an issue.
