### ISSUE TITLE
extendType should create a new type not alter the base

### ISSUE THREAD

**Issue by kevin-daniel-hunt** [graphql-nexus/nexus#857]
```javascript
export const Test = objectType({
  name: 'Test',
  definition(t) {
    // ...
  }
})

export const ExtendedTest = extendType({
  type: 'Test',
  definition(t) {
    // add additional fields
  }
})

const schema = makeSchema({
  types: [Test, ExtendedTest] // Pass both types here
})
```

Consider the above example.  This does not create a new type available for use called "ExtendedTest" which consists of the Test types fields as well as its newly defined ones, it instead modifies the base type of "Test" to have those additional fields.  This feels anti-pattern to how we define new types by extending base types.

**Comment by otrebu** [comment]
I believe `extendType` is used a lot when declaring query and mutation in different files.

**Comment by Sytten** [comment]
This is the way graphql works. If you extend a type a one place it becomes available to everybody else at the same time (aka there is no loading order or access/privacy modifiers). This is behaviour is expected and the correct one.

**Comment by fr33z3** [comment]
> I believe `extendType` is used a lot when declaring query and mutation in different files.

Could you provide an example to do that? Because that is what I'm trying to achieve but can not figure this out.
