### ISSUE TITLE
Broken link - Tutorial Section 02 

### ISSUE THREAD

**Issue by aseerkt** [graphql-nexus/nexus#858]
There is a broken link which takes it to home-page instead of its specified location.
Page: [Getting Started / Tutorial : 2. Writing your first schema](https://nexusjs.org/docs/getting-started/tutorial/chapter-writing-your-first-schema/)

![nexus-broken-link](https://user-images.githubusercontent.com/39845171/111074065-62930680-8507-11eb-8e77-7b04277b3fce.png)

**Comment by yashguptaz** [comment]
@tgriesser Can we close this issue now as the PR has got merged?
