### ISSUE TITLE
Missing field in type definition need to resolve a 1-n relationship

### ISSUE THREAD

**Issue by binajmen** [graphql-nexus/nexus#860]
Hi everyone,

I have two PostgreSQL tables `Category` and `Place`. One category has 1 place. A place has multiple categories.

I have a foreign key `placeId` in `Category` that points to one `Place.id` When introspecting the database with prisma, and generating the types, I have the following output:

```js
// node_modules/.prisma/client/index.d.ts
...
/**
 * Model Category
 */

export type Category = {
  id: number
  name: string
  order: number
  placeId: number
}

/**
 * Model Place
 */

export type Place = {
  id: number
  name: string
}
...
```
So far so good. Below is the GraphQL resolver for `Category`:
```js
import { objectType, inputObjectType } from "nexus"

export const Category = objectType({
  name: "Category",
  definition(t) {
    t.nonNull.int("id")
    t.nonNull.string("name")
    t.nonNull.int("order")
    t.field("place", {
      type: "Place",
      resolve: (parent, _, ctx) => {
        return ctx.db.place
          .findUnique({
            where: { id: parent.placeId }, // <--- TS error here
          })
      },
    })
  },
})
```
I have the typescript error: `Property 'placeId' does not exist on type '{ id: number; name: string; order: number; }'.ts(2339)`

I build the schema using nexus:
```js
export const schema = makeSchema({
  types,
  outputs: {
    typegen: join(__dirname, ".", "nexus-typegen.ts"),
    schema: join(__dirname, ".", "schema.GraphQL"),
  },
  ...
})
```
The `schema.GraphQL` output is the following:
```js
type Category {
  id: Int!
  name: String!
  order: Int!
  place: Place
}

type Place {
  categories: [Category!]!
  id: Int!
  name: String!
}
```
And the `nexus-typegen.ts` output is the following:
```js
export interface NexusGenFieldTypes {
  Category: { // field return type
    id: number; // Int!
    name: string; // String!
    order: number; // Int!
    place: NexusGenRootTypes['Place'] | null; // Place
  }
  ...
```
I noticed that `placeId` is not defined in `nexus-typegen.ts` which is probably causing the TS error.

Am I doing something wrong?

**Comment by binajmen** [comment]
Adding `t.nonNull.int("placeId")` would solve the TS error. However, it means that `fieldId` is available in the schema..

I saw that we can specify `sourceTypes` in `makeSchema`:
```js
  sourceTypes: {
    modules: [{ module: '.prisma/client', alias: 'PrismaClient' }],
  },
```
Is it the correct way to solve this?

**Comment by otrebu** [comment]
Have you looked into the `sourceTypes` config option on `makeSchema`?

https://nexusjs.org/docs/api/make-schema#shouldgenerateartifacts-outputs-sourcetypes

```
sourceTypes: {
    modules: [
      {
        module: require.resolve(".prisma/client/index.d.ts"),
        alias: "dbt",
      },
    ],
  },
  ```
  
  This should solve your issue

**Comment by Sytten** [comment]
@binajmen like @otrebu mentioned, you need to make the graphql type to your prisma type. This is done using source types.
