### ISSUE TITLE
Is there a way to rename root types?

### ISSUE THREAD

**Issue by cypcz** [graphql-nexus/nexus#867]
Hi all,

I ran into same issue as [here](https://github.com/dotansimha/graphql-code-generator/issues/3893). I have 2 schemas I'd like to generate types for, but one of those schemas (3rd party) has root type for query named `QueryRoot`, while Nexus (my schema) names this root type `Query`, therefore these 2 root types are not merged together in the final schema.

I'd like to avoid schema stitching, if possible. I'm thinking the easiest way to solve this particular issue would be to rename root query from Nexus to `QueryRoot`. Is this possible? If so, how?

**Comment by tgriesser** [comment]
Interesting, I had held off on making this an option until there was a valid use-case. I think it'd be reasonable to allow configuring the naming here.

**Comment by ShanonJackson** [comment]
@tgriesser 
Please can you add this? We've got completely identical problem; We use schema stitching to stitch Hasura's schema and Nexus's schema togeather; and the different QueryRoot names is a huge issue.

We currently have no way to solve this, and its effecting our GraphQL Codegen.

Any idea of when this could be added?
