### ISSUE TITLE
Support pulling source types from "export type" syntax

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/nexus#870]
When `--isolate-modules` is enabled (in a Next.js app for example) it is required to use `export type` syntax.

![image](https://user-images.githubusercontent.com/284476/112376049-5ef74080-8cba-11eb-8628-f0d0f0efd2c2.png)

Nexus doesn't support pulling from this pattern. Needs a regex update.

**Comment by tgriesser** [comment]
Ah yeah, good idea. Also need to update the generated nexus typings to `import type`

**Comment by tom-sherman** [comment]
This looks to have mainly been fixed by #872. My PR also cleans up the internals to support isolated modules as well

**Comment by tom-sherman** [comment]
@jasonkuhrt Following on from our conversation in #917, does #872 not solve this issue?

**Comment by tgriesser** [comment]
@tom-sherman I think what @jasonkuhrt was referring to was pulling from the `export type { ... }` but the regex never supported pulling from object literal export syntax anyway, so yeah I think this can be closed for now.
