### ISSUE TITLE
Nexus Tutorial Part 4. Testing your API fails npm run test

### ISSUE THREAD

**Issue by raleigh9123** [graphql-nexus/nexus#878]
I'm working through the Nexus tutorial and encounter an error when running the command "npm run test". I have included a screenshot of the terminal output of the command and can't seem to figure out the problem. 

I have the following versions installed in my package.json
```json
"dependencies": {
    "apollo-server": "^2.22.2",
    "graphql": "^15.5.0",
    "nexus": "^1.0.0"
  },
  "devDependencies": {
    "@types/jest": "^26.0.22",
    "get-port": "^5.1.1",
    "graphql-request": "^3.4.0",
    "jest": "^26.6.3",
    "ts-jest": "^26.5.4",
    "ts-node-dev": "^1.1.6",
    "typescript": "^4.2.3"
  }
```

<img width="791" alt="Screen Shot 2021-04-05 at 2 14 15 PM" src="https://user-images.githubusercontent.com/41349450/113629801-c054d300-961b-11eb-9655-067d914003a8.png">

Perhaps an important note, the tutorial also misses including an export statement in the *server.ts* file located in */api/server.ts*. 
The export statement was not included in any of the previous tutorial chapters but is imported as a module in *tests/__helper.ts* on line 4.

**Comment by raleigh9123** [comment]
Continued on to part **6. Testing with Prisma**, and basically got the same terminal response back after running *npm run test* command. I have never used jest before. Just learning how to use these tools, and I have no idea where to start to fix this issue.

**Comment by gatherKnowledge** [comment]
me either.

**Comment by ruheni** [comment]
Hi @raleigh9123 👋🏾

Thank you for creating this issue. I tested it locally and ran into the same issue.

>Perhaps an important note, the tutorial also misses including an export statement in the server.ts file located in /api/server.ts.

You are right, this is one of the fixes to the tutorial.

I updated the tutorial recently and I have a hunch it broke the tests. 

Update your `server.ts` file to resemble this:
```javascript
import { ApolloServer } from 'apollo-server'
import { schema } from './schema'
import { context } from './context'

export const server = new ApolloServer({ schema, context })
```

Create `app.ts` file in the api folder and import `server` as follows:

```javascript
 import { server } from "./server";

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`)
})
```

Lastly, update your `package.json` scripts to point the `dev` script to `app.ts`:
```json
  "scripts": {
    "dev": "ts-node-dev --transpile-only --no-notify api/app.ts",
    "build": "tsc",
    "generate": "ts-node --transpile-only api/schema",
    "test": "npm run generate && jest"
  },
```

Re-run your tests and let me know if you run into any issues. 🙂

We'll update the tutorial soon fixing this error.

**Comment by raleigh9123** [comment]
This did solve the problem I encountered! Thank you.

When running the command again, I did receive an error that Jest could not find the node module "Prettier" Installing prettier as a dev dependency cleared this error and the test runs successfully.

**Comment by jasonkuhrt** [comment]
Going to keep this open until you've updated the tutorial @ruheni, thanks!
