### ISSUE TITLE
Error on self reference field on resolve type 

### ISSUE THREAD

**Issue by mandado** [graphql-nexus/nexus#891]
Hello guys, 

So I`m trying to access self field using root on my objectType, but I cannot do this, because typescript complains that field doesn't exists.

How can I solve that problem ?
![image](https://user-images.githubusercontent.com/2823627/114803781-7c2da500-9d76-11eb-8b24-0614f91bf6bb.png)

**Comment by otrebu** [comment]
Is the root type in this case a User? 
The User fields should be available straight from root.

**Comment by mandado** [comment]
No, the root type is called **Property**, the type **User** is the type of data that will be returned. **pickedUpBy** is field that belongs to only **Property** Document, but it's used to find the correspondent user on **User** Document.

I don't if this change something, but I'm using mongodb as database.

**Comment by otrebu** [comment]
Ah yes, so in this case from your root type `Property` you will be able to access only the fields that have already been resolved. 

I don't think you are allowed to access the same field you are resolving. It won't be available, that is what you are trying to resolve.

If for example your Property has a `userId`, and that has been retrieved has part of the resolve chain, and it is part of your root type ( look into customising your root types in the `makeSchema` configs ) then you can use that to retrieve your User.

**Comment by mandado** [comment]
I guess that I don't understand the last sentence. can you give me an example to help me ?

**Comment by otrebu** [comment]
There could be two different types. 

- The types that represent the shape of the data in your database
-  The types that represent the graphQL schema.

Sometimes they are the same, but most times they are at least a bit different.

Here is an example:

```

export const Property = objectType({
  name: "Property",
  definition(t) {
    t.implements(Node);
    t.string("name");
    t.nonNull.field("user", {
      type: User,
      resolve(root, args, context) {
        if (!root.userId) {
          throw new Error("Id is needed to request posts");
        }
        return context.db.post.findMany({
          where: {
            post: {
              userId: root.userId,
            },
          },
        });
      },
    });
  },
});
```

**Comment by mandado** [comment]
nice! I'll try to apply something like this!, thank you so much!
