### ISSUE TITLE
Computed inputs for `where`

### ISSUE THREAD

**Issue by Varal7** [graphql-nexus/nexus#902]
Hi,

I'm using nexus with the prisma plugin and trying to use the experimental crud feature.
The computed inputs work great when trying to create an element, since we can easily `connect` to the user field using `computedInputs`.
However, when trying to update a table linked to a certain user, is there a way to have the `where` object be computed at runtime?

**Comment by Sytten** [comment]
The nexus plugin is not supported by this repository.
The current prisma plugin being deprecated, I invite you to check the new one there https://github.com/prisma/nexus-prisma/
