### ISSUE TITLE
Wrong type generated by nullable() + default value

### ISSUE THREAD

**Issue by Anomen** [graphql-nexus/nexus#921]
Hi,

I'm currently in the process of updating `nexus` from `^0.11.7` to `^1.0.0`. 

My code looks like that:

```
orderBy: arg({
    type: nullable("PhotosOrderBy"),
    default: "DATE_DESC",
  })
```

In version `^0.11.7`, here is the typescript output:

```typescript
orderBy?: NexusGenEnums["PhotosOrderBy"] | null; // PhotosOrderBy
```

But in `^1.0.0`, the typescript output is:

```typescript
orderBy: NexusGenEnums["PhotosOrderBy"] | null; // PhotosOrderBy
```

The `graphql` output stayed the same:

```
/* ... */ orderBy: PhotosOrderBy = DATE_DESC /* .... */
``` 

---

Basically, the field is not optional anymore, even if there is a default value.

Is this a bug?

Thanks!

PS: for more context, please check the [2 comments on this PR on my project](https://github.com/vickev/howdypix/pull/299/files#diff-1fc446ddb4f0281fd448e88de940769c72f038523cb3d00a671b3c58e3302783).

**Comment by Sytten** [comment]
If you can create a minimal repro that would help, thanks!

**Comment by tgriesser** [comment]
> Basically, the field is not optional anymore, even if there is a default value.

> Is this a bug?

@Anomen I closed this in https://github.com/graphql-nexus/nexus/pull/965 but I'm realizing now that this might be an incorrect change. Basically this is used for the typings of the `args` provided to the resolver, and if you've provided a `default` value, then it will be used if none is provided.

Does this make sense?

**Comment by Sytten** [comment]
Lets be careful with default values, they are not super obvious in GraphQL.js

If the field is nullable that means the user can explicitely pass null. I think only undefined must be removed (need to double check that) since that will use the default.
