### ISSUE TITLE
Add eslint disable on top of typegen file

### ISSUE THREAD

**Issue by nenadfilipovic** [graphql-nexus/nexus#926]
Did anyone managed to achieve this and how?
I could ignore it in eslint config but this is my preferred way.

**Comment by tgriesser** [comment]
You can customize it via `formatTypegen` option to `makeSchema`: https://github.com/graphql-nexus/nexus/blob/690abb7299c52f57519521c47a466be1a3ed88b2/src/builder.ts#L220-L224

**Comment by nenadfilipovic** [comment]
Very nice thanks, it would be nice to put example in documentation if there is not already, I didn't managed to find example there.
```
formatTypegen: (content) => {
    return `/* eslint-disable */ \n ${content}`;
  },
```

**Comment by jasonkuhrt** [comment]
@nenadfilipovic PR welcome!
