### ISSUE TITLE
Error: DateTime was already defined and imported as a type, check the docs for extending types

### ISSUE THREAD

**Issue by btodorce** [graphql-nexus/nexus#929]
Not sure is this a bug might be me improperly using grpahql nexus. 
Current stack is graphql nexus, prisma 2. Apollo server + using prisma-tools to generate crud for a set number of db tables. Trying to extend/overwrite overwrite the default DateTime, to handle cases like non RFC 3339 dates and custom date types with one DateTime scalar. But each time the scalar is added as a type to makeSchema this error is being thrown.

**Comment by Sytten** [comment]
This is not an error of nexus, I believe the plugin is creating a datetime scalar since this is not something built-in of graphql.
The current plugin is deprecated but you should check with the devs for the new plugin: https://github.com/prisma/nexus-prisma
