### ISSUE TITLE
how to make graphql without model?

### ISSUE THREAD

**Issue by hiphapis** [graphql-nexus/nexus#953]
I just make a signin with JWT. but something wrong.
And i also saw https://github.com/Camji55/nexus-plugin-jwt-auth/blob/develop/examples/basic-permissions/api/graphql/Mutation.ts And try like this code. unfortunately same error. 
```
Error: 
- Missing type AuthPayload, did you forget to import a type to the root query?
```
Code is here
```javascript
export const AuthPayload = objectType({
  name: 'AuthPayload',
  definition(t) {
    t.string('token')
    t.field('user', { type: 'user' })
  },
})

export const Signin = extendType({
  type: 'Mutation',
  definition(t) {
    t.field('Signin', {
      type: 'AuthPayload',
      resolve(_, __, ctx) {
        return {
          token: "abcd",
          user: ctx.prisma.user.findUnique({ where: { id: 1 }})
        };
      }
    })
  }
})
```
What is the problem?

**Comment by tgriesser** [comment]
Change `type: 'AuthPayload'` to `type: AuthPayload` and/or ensure that `AuthPayload` is imported into the `types` option for `makeSchema`

**Comment by hiphapis** [comment]
@tgriesser Huh..? Seriously? hahaha. i'm so stupid. Thx @tgriesser !!!
