### ISSUE TITLE
How do I get it from query to "ctx.currentUser.post.comment" in this way?

### ISSUE THREAD

**Issue by qkrdkwl9090** [graphql-nexus/nexus#958]
We are going to extract DB data that is matched at 1:N from prisma from query. For example, post tables and comment tables. How do I get it from query to "ctx.currentUser.post.comment" in this way? Currently, "undefined" appears, and the foreign key is set in PRISMA.

**Comment by tgriesser** [comment]
Sounds like a question for prisma, not nexus.
